package com.folder.boot.controller;

import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.folder.boot.dto.Notice;

@RestController
@CrossOrigin(origins = "*")
@RequestMapping("/Notice")
public class NoticeController {

  @PostMapping("/List")
  public List<?> list() {
    List<Notice> list = new ArrayList<Notice>();
    Notice notice = new Notice();
    notice.setNo(1);
    notice.setTitle("연습용 1");
    notice.setRegDate(new Date().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime());
    notice.setDesc("스타일리시한 세 가지 케이스 색상. 건강과 피트니스에 대한 통찰을 제공하는 강력한 센서. 혁신적인 안전 기능. 끊김 없이 소통을 유지하는 편리한 방법. 여기에 한층 향상된 성능을 위한 더 빠른 듀얼 코어 프로세서까지. 수많은 기능들로 가득 찬 Apple Watch SE, 그 어느 때보다도 탁월한 가성비를 자랑합니다.");
    list.add(notice);
    return list;
  }

  @PostMapping("/findById")
  public Map<String, Object> findById(@RequestBody Map<String, Object> map) {
    Map<String, Object> resultMap = new HashMap<String, Object>();
    String result = "JTdCJTIydGltZSUyMiUzQTE2ODE2MzkwNzM1NzIlMkMlMjJibG9ja3MlMjIlM0ElNUIlN0IlMjJpZCUyMiUzQSUyMm43aE0xNjdXcTUlMjIlMkMlMjJ0eXBlJTIyJTNBJTIyaGVhZGVyJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnRleHQlMjIlM0ElMjJFZGl0b3IuanMlMjIlMkMlMjJsZXZlbCUyMiUzQTIlN0QlN0QlMkMlN0IlMjJpZCUyMiUzQSUyMndKcEtFMTk4TlYlMjIlMkMlMjJ0eXBlJTIyJTNBJTIycGFyYWdyYXBoJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMnRleHQlMjIlM0ElMjJIZXkuJTIwTWVldCUyMHRoZSUyMG5ldyUyMEVkaXRvci4lMjBPbiUyMHRoaXMlMjBwYWdlJTIweW91JTIwY2FuJTIwc2VlJTIwaXQlMjBpbiUyMGFjdGlvbiUyMCVFMiU4MCU5NCUyMHRyeSUyMHRvJTIwZWRpdCUyMHRoaXMlMjB0ZXh0LiUyMFNvdXJjZSUyMGNvZGUlMjBvZiUyMHRoZSUyMHBhZ2UlMjBjb250YWlucyUyMHRoZSUyMGV4YW1wbGUlMjBvZiUyMGNvbm5lY3Rpb24lMjBhbmQlMjBjb25maWd1cmF0aW9uLiUyMiU3RCU3RCUyQyU3QiUyMmlkJTIyJTNBJTIyZExGYnY1YkhfaiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJoZWFkZXIlMjIlMkMlMjJkYXRhJTIyJTNBJTdCJTIydGV4dCUyMiUzQSUyMktleSUyMGZlYXR1cmVzJTIyJTJDJTIybGV2ZWwlMjIlM0EzJTdEJTdEJTJDJTdCJTIyaWQlMjIlM0ElMjI3N25ZbWtNb0h6JTIyJTJDJTIydHlwZSUyMiUzQSUyMmxpc3QlMjIlMkMlMjJkYXRhJTIyJTNBJTdCJTIyc3R5bGUlMjIlM0ElMjJ1bm9yZGVyZWQlMjIlMkMlMjJpdGVtcyUyMiUzQSU1QiU3QiUyMmNvbnRlbnQlMjIlM0ElMjJBcHBsZXMlMjIlMkMlMjJpdGVtcyUyMiUzQSU1QiU3QiUyMmNvbnRlbnQlMjIlM0ElMjJSZWQlMjIlMkMlMjJpdGVtcyUyMiUzQSU1QiU1RCU3RCUyQyU3QiUyMmNvbnRlbnQlMjIlM0ElMjJHcmVlbiUyMiUyQyUyMml0ZW1zJTIyJTNBJTVCJTVEJTdEJTVEJTdEJTJDJTdCJTIyY29udGVudCUyMiUzQSUyMkJhbmFuYXMlMjIlMkMlMjJpdGVtcyUyMiUzQSU1QiU3QiUyMmNvbnRlbnQlMjIlM0ElMjJZZWxsb3clMjIlMkMlMjJpdGVtcyUyMiUzQSU1QiU1RCU3RCU1RCU3RCU1RCU3RCU3RCUyQyU3QiUyMmlkJTIyJTNBJTIydWtocGFZampWYiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJwYXJhZ3JhcGglMjIlMkMlMjJkYXRhJTIyJTNBJTdCJTIydGV4dCUyMiUzQSUyMkNyZWF0ZSUyMGElMjBkaXJlY3RvcnklMjBmb3IlMjB5b3VyJTIwbW9kdWxlJTJDJTIwZW50ZXIlMjBpdCUyMGFuZCUyMHJ1biUyMCUzQ2NvZGUlMjBjbGFzcyUzRCU1QyUyMmlubGluZS1jb2RlJTVDJTIyJTNFbnBtJTIwaW5pdCUzQyUyRmNvZGUlM0UlMjBjb21tYW5kLiUyMiU3RCU3RCUyQyU3QiUyMmlkJTIyJTNBJTIyUTJtaDJqU25BeiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJxdW90ZSUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJ0ZXh0JTIyJTNBJTIyV2UlMjBoYXZlJTIwYmVlbiUyMHdvcmtpbmclMjBvbiUyMHRoaXMlMjBwcm9qZWN0JTIwbW9yZSUyMHRoYW4lMjB0aHJlZSUyMHllYXJzLiUyMFNldmVyYWwlMjBsYXJnZSUyMG1lZGlhJTIwcHJvamVjdHMlMjBoZWxwJTIwdXMlMjB0byUyMHRlc3QlMjBhbmQlMjBkZWJ1ZyUyMHRoZSUyMEVkaXRvciUyQyUyMHRvJTIwbWFrZSUyMGl0cyUyMGNvcmUlMjBtb3JlJTIwc3RhYmxlLiUyMEF0JTIwdGhlJTIwc2FtZSUyMHRpbWUlMjB3ZSUyMHNpZ25pZmljYW50bHklMjBpbXByb3ZlZCUyMHRoZSUyMEFQSS4lMjBOb3clMkMlMjBpdCUyMGNhbiUyMGJlJTIwdXNlZCUyMHRvJTIwY3JlYXRlJTIwYW55JTIwcGx1Z2luJTIwZm9yJTIwYW55JTIwdGFzay4lMjBIb3BlJTIweW91JTIwZW5qb3kuJTIwJUYwJTlGJTk4JThGJTIyJTJDJTIyY2FwdGlvbiUyMiUzQSUyMldoYXQlMjBkb2VzJTIwaXQlMjBtZWFuJTIwJUMyJUFCYmxvY2stc3R5bGVkJTIwZWRpdG9yJUMyJUJCJTIyJTJDJTIyYWxpZ25tZW50JTIyJTNBJTIybGVmdCUyMiU3RCU3RCUyQyU3QiUyMmlkJTIyJTNBJTIyN0ZQTjJwTkFJRCUyMiUyQyUyMnR5cGUlMjIlM0ElMjJ0YWJsZSUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJ3aXRoSGVhZGluZ3MlMjIlM0F0cnVlJTJDJTIyY29udGVudCUyMiUzQSU1QiU1QiUyMktpbmUlMjIlMkMlMjJQaWdzJTIyJTJDJTIyQ2hpY2tlbiUyMiU1RCUyQyU1QiUyMjElMjBwY3MlMjIlMkMlMjIzJTIwcGNzJTIyJTJDJTIyMTIlMjBwY3MlMjIlNUQlMkMlNUIlMjIxMDAlMjQlMjIlMkMlMjIyMDAlMjQlMjIlMkMlMjIxNTAlMjQlMjIlNUQlNUQlN0QlN0QlMkMlN0IlMjJpZCUyMiUzQSUyMjI1akwtOE1MbHAlMjIlMkMlMjJ0eXBlJTIyJTNBJTIyY29kZSUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJjb2RlJTIyJTNBJTIyKiUyMCU3QiU1Q24lMjAlMjBtYXJnaW4lM0ElMjAwJTNCJTVDbiUyMCUyMHBhZGRpbmclM0ElMjAwJTNCJTVDbiUyMCUyMGJveC1zaXppbmclM0ElMjBib3JkZXItYm94JTNCJTVDbiUyMCUyMGZvbnQtZmFtaWx5JTNBJTIwJ0ZpcmElMjBTYW5zJyUyQyUyMHNhbnMtc2VyaWYlM0IlNUNuJTIwJTIwJTI2JTNBJTNBc2VsZWN0aW9uJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGJhY2tncm91bmQlM0ElMjB0cmFuc3BhcmVudGl6ZSglMjM0MkI4ODMlMkMlMjAwLjUpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlMjIlN0QlN0QlMkMlN0IlMjJpZCUyMiUzQSUyMkx6WWlRRGFQQU4lMjIlMkMlMjJ0eXBlJTIyJTNBJTIyZGVsaW1pdGVyJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiU3RCU3RCUyQyU3QiUyMmlkJTIyJTNBJTIyRjNxSXppYWszbiUyMiUyQyUyMnR5cGUlMjIlM0ElMjJpbWFnZSUyMiUyQyUyMmRhdGElMjIlM0ElN0IlMjJmaWxlJTIyJTNBJTdCJTIydXJsJTIyJTNBJTIyJTJGbG9nby5wbmclMjIlMkMlMjJzaXplJTIyJTNBMTg4OTklMkMlMjJuYW1lJTIyJTNBJTIybG9nby5wbmclMjIlMkMlMjJleHRlbnNpb24lMjIlM0ElMjJwbmclMjIlN0QlMkMlMjJjYXB0aW9uJTIyJTNBJTIyJUVCJUExJTlDJUVBJUI3JUI4JTIwJUVDJTlEJUI0JUVCJUFGJUI4JUVDJUE3JTgwJTIwJUVDJTlFJTg1JUVCJThCJTg4JUVCJThCJUE0LiUyMiUyQyUyMndpdGhCb3JkZXIlMjIlM0FmYWxzZSUyQyUyMnN0cmV0Y2hlZCUyMiUzQWZhbHNlJTJDJTIyd2l0aEJhY2tncm91bmQlMjIlM0F0cnVlJTdEJTdEJTJDJTdCJTIyaWQlMjIlM0ElMjJsSGhyVGhYMWdqJTIyJTJDJTIydHlwZSUyMiUzQSUyMmF0dGFjaGVzJTIyJTJDJTIyZGF0YSUyMiUzQSU3QiUyMmZpbGUlMjIlM0ElN0IlMjJ1cmwlMjIlM0ElMjIlMkZsb2dvLnBuZyUyMiUyQyUyMnNpemUlMjIlM0ExODg5OSUyQyUyMm5hbWUlMjIlM0ElMjJsb2dvLnBuZyUyMiUyQyUyMmV4dGVuc2lvbiUyMiUzQSUyMnBuZyUyMiU3RCUyQyUyMnRpdGxlJTIyJTNBJTIyTG9nbyUyMiU3RCU3RCU1RCUyQyUyMnZlcnNpb24lMjIlM0ElMjIyLjI2LjUlMjIlN0Q=";
    resultMap.put("content", result);
    resultMap.put("no", Integer.parseInt(map.get("no").toString()));
    resultMap.put("title", "연습용");
    resultMap.put("desc", "Editor.js를 이용한 Notice 화면입니다.");
    resultMap.put("state", true);
    return resultMap;
  }

  @PutMapping("/save")
  public Notice save(@RequestBody Notice notice) {
    System.out.println(notice);
    notice.setNo(1);
    return notice;
  }

}
