USE edu;

CREATE OR REPLACE TABLE FILE (
	`no`		INT				NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	`name`		VARCHAR(100)	NOT NULL,
	`extension`	VARCHAR(50)		NOT NULL,
	`url`		VARCHAR(200)	NOT NULL,
	`saveName`	VARCHAR(100)	NOT NULL,
	`savePath`	VARCHAR(200)	NOT NULL,
	`del`		BOOLEAN			NOT NULL	DEFAULT FALSE,
	`regDate`	DATETIME		NOT NULL	DEFAULT NOW(),
	`alterDate`	DATETIME		NOT NULL	DEFAULT NOW()
);

CREATE OR REPLACE TABLE USER (
	`no`		INT				NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	`name`		VARCHAR(100)	NOT NULL,
	`email`		VARCHAR(200)	NOT NULL,
	`pwd`		VARCHAR(100)	NOT NULL,
	`del`		BOOLEAN			NOT NULL	DEFAULT FALSE,
	`joinDate`	DATETIME		NOT NULL	DEFAULT NOW(),
	`alterDate`	DATETIME		NOT NULL	DEFAULT NOW(),
	`fileNo`	INT				NOT NULL	DEFAULT 1,
	FOREIGN KEY(`fileNo`) REFERENCES FILE(`no`)
);

CREATE OR REPLACE TABLE NOTICE (
	`no`		INT				NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	`title`		VARCHAR(100)	NOT NULL,
	`desc`		VARCHAR(255)	NULL,
	`content`	TEXT(30000)		NULL,
	`del`		BOOLEAN			NOT NULL	DEFAULT FALSE,
	`regDate`	DATETIME		NOT NULL	DEFAULT NOW(),
	`alterDate`	DATETIME		NOT NULL	DEFAULT NOW(),
	`userNo`	INT				NOT NULL,
	FOREIGN KEY(`userNo`) REFERENCES USER(`no`)
);

commit;
