USE edu;

CREATE OR REPLACE TABLE FILE (
	`no`				INT						NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	`name`			VARCHAR(100)	NOT NULL,
	`extension`	VARCHAR(50)		NOT NULL,
	`url`				VARCHAR(200)	NOT NULL,
	`saveName`	VARCHAR(100)	NOT NULL,
	`savePath`	VARCHAR(200)	NOT NULL,
	`mediaType`	VARCHAR(100)	NOT NULL,
	`del`				BOOLEAN				NOT NULL	DEFAULT FALSE,
	`regDate`		DATETIME			NOT NULL	DEFAULT NOW(),
	`alterDate`	DATETIME			NOT NULL	DEFAULT NOW()
);

CREATE OR REPLACE TABLE USER (
	`no`				INT						NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	`name`			VARCHAR(100)	NOT NULL,
	`email`			VARCHAR(200)	NOT NULL,
	`pwd`				VARCHAR(100)	NOT NULL,
	`del`				BOOLEAN				NOT NULL	DEFAULT FALSE,
	`joinDate`	DATETIME			NOT NULL	DEFAULT NOW(),
	`alterDate`	DATETIME			NOT NULL	DEFAULT NOW(),
	`fileNo`		INT						NULL,
	FOREIGN KEY(`fileNo`) REFERENCES FILE(`no`)
);

CREATE OR REPLACE TABLE NOTICE (
	`no`				INT						NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
	`title`			VARCHAR(100)	NOT NULL,
	`desc`			VARCHAR(255)	NULL,
	`content`		TEXT(30000)		NULL,
	`del`				BOOLEAN				NOT NULL	DEFAULT FALSE,
	`regDate`		DATETIME			NOT NULL	DEFAULT NOW(),
	`alterDate`	DATETIME			NOT NULL	DEFAULT NOW(),
	`userNo`		INT						NOT NULL,
	FOREIGN KEY(`userNo`) REFERENCES USER(`no`)
);

INSERT INTO user
	(name, email, pwd)
VALUE
	('folder', 'folder@email.com', '1234');

INSERT INTO user
	(name, email, pwd)
VALUE
	('사용자', 'user@email.com', '1234');

CREATE OR REPLACE TABLE NOTICE_CNT (
	`noticeNo`	INT				NOT NULL,
	`userNo`		INT				NOT NULL,
	`regDate`		DATETIME	NOT NULL	DEFAULT NOW()
);

commit;
